version: '3'
volumes:
  dados:
networks:
  banco:
  web:
  fila:
services:
    db: 
      image:  postgres:9.6
      volumes:
        #Volume de dados
        - dados:/var/lib/postgresql/data
        #script
        - ./scripts:/scripts
        - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql # tudo que é copiado para a pasta docker-entrypoint-initdb.d é iniciado quando  banco sobe
      networks:
        - banco
    frontend:
      image: nginx:1.13
      volumes:
        #Site
        - ./web:/usr/share/nginx/html
        #configuração do proxy reverso -- nessa linha eu substituo o arquivo padrao do nginx pelo que eu criei em minha maquina, a unica conf diferente é o proxy reverso
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
      networks:
        - web
      depends_on: #deve subir o container app antes do frontend
        - app
    app:
      image: python:3.6
      volumes: 
        #Aplicação
        - ./app:/app
      working_dir: /app
      command: bash ./app.sh
      networks:
        - banco
        - web
        - fila
      depends_on:
        - db
        - queue
     # por causa do proxy reverso nao preciso expor a porta 8080 do backend
     # ports:
     #   - 8080:8080
    queue:
      image: redis:3.2
      networks:
        - fila
    
    worker:
     # image: python:3.6 //trocando para pegar um imagem pronta
      build: worker
      volumes:
        # Worker
      - ./worker:/worker
      working_dir: /worker
     # command: bash ./app.sh  // o mesmo acima
      command: worker.py
      networks:
        - fila
      depends_on:
        - queue